metadata:
  Memory Total:
    units: MB
    precision: 0
    larger_is_better: true
  Memory Used:
    units: MB
    precision: 0
  Memory Available:
    units: MB
    precision: 0
  "% Memory Used":
    units: "%"
    precision: 0
  Swap Total:
    units: MB
    precision: 0
  Swap Used:
    units: MB
    precision: 0
  "% Swap Used":
    units: "%"
    precision: 0

triggers:
  - type: peak
    dname: "% Swap Used"
    max_value: 50
